name = "emailprodigy"
main = "index.js"
compatibility_date = "2026-03-28"

[vars]
RESEND_API_KEY = "re_bfP2aN2c_7x7HrkUAcF5uYVVhqPtocpzP"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
